---  
- set_fact: 
    tower_password: "{{ lookup('vars', item + '_tower_password' ) }}"
    tower_license: "{{ lookup('vars', item + '_tower_license' ) }}"
    
- include_tasks: encrypt_variables.yml
  with_items: 
        - { name: '{{ item }}_tower_password', value: '{{ tower_password }}' }
        - { name: '{{ item }}_tower_license', value: '{{ tower_license }}' }
  no_log: true

- set_fact: 
    tower_host: "{{ lookup('vars', item + '_tower_host' ) }}"
    tower_verify_ssl: "{{ lookup('vars', item + '_tower_verify_ssl' ) }}"
    tower_username: "{{ lookup('vars', item + '_tower_username' ) }}"
    tower_password_enc: "{{ lookup('vars', item + '_tower_password_enc' ) }}"
    tower_license_enc: "{{ lookup('vars', item + '_tower_license_enc' ) }}"

- name: Template tower credentials
  template: 
    src: tower_credentials/tower_credentials.yml.j2
    dest: inventories/group_vars/all/{{ item }}_tower_credentials_list.yml