---  
- set_fact: 
    social_auth_github_org_key: "{{ lookup('vars', item + '_social_auth_github_org_key' ) }}"
    social_auth_github_org_secret: "{{ lookup('vars', item + '_social_auth_github_org_secret' ) }}"
    
- include_tasks: encrypt_credentials.yml
  with_items: 
        - { name: '{{ item }}_social_auth_github_org_key', value: '{{ social_auth_github_org_key }}' }
        - { name: '{{ item }}_social_auth_github_org_secret', value: '{{ social_auth_github_org_secret }}' }
  no_log: true

- set_fact: 
    social_auth_github_org_name: "{{ lookup('vars', item + '_social_auth_github_org_name' ) }}"
    social_auth_github_org_organization_map: "{{ lookup('vars', item + '_social_auth_github_org_organization_map' ) }}"
    social_auth_github_org_team_map: "{{ lookup('vars', item + '_social_auth_github_org_team_map' ) }}"
    social_auth_github_org_key_enc: "{{ lookup('vars', item + '_social_auth_github_org_key_enc' ) }}"
    social_auth_github_org_secret_enc: "{{ lookup('vars', item + '_social_auth_github_org_secret_enc' ) }}"

- name: Template GitHub credentials
  template: 
    src: github_credentials/github_credentials.yml.j2
    dest: inventories/group_vars/all/{{ item }}_github_authentication.yml